### ISSUE TITLE
How to rest summernote

### ISSUE THREAD

**Issue by GJ2511** [Vnkitaev/react-summernote#10]
I uses ReactSummernote.reset()

but this result in an error

Uncaught (in promise) TypeError: Cannot read property 'summernote' of undefined(…)

![error](https://cloud.githubusercontent.com/assets/5977203/18990102/6a705d26-872d-11e6-9a52-9e39343e6ae8.png)

**Comment by Vnkitaev** [comment]
What version of Summernote are you using? 

I'm asking because the bug you are talking about was fixed in version 1.0.3
