### ISSUE TITLE
ReferenceError: navigator is not defined, Meteor project

### ISSUE THREAD

**Issue by pandabrand** [Vnkitaev/react-summernote#12]
Hi,  
I'm not using webpack, I have a meteor project where I am using react components. When I start up my app I get the following error:  

```
W20161026-21:37:12.911(-5)? (STDERR) ReferenceError: navigator is not defined
W20161026-21:37:12.912(-5)? (STDERR)     at Object.<anonymous> (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:594:20)
W20161026-21:37:12.912(-5)? (STDERR)     at eq (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:229:229)
W20161026-21:37:12.913(-5)? (STDERR)     at Object.module.exports (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:237:3)
W20161026-21:37:12.914(-5)? (STDERR)     at __webpack_require__ (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:30:30)
W20161026-21:37:12.915(-5)? (STDERR)     at Object.<anonymous> (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:65:2)
W20161026-21:37:12.915(-5)? (STDERR)     at Object.module.exports (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:203:31)
W20161026-21:37:12.916(-5)? (STDERR)     at __webpack_require__ (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:30:30)
W20161026-21:37:12.916(-5)? (STDERR)     at Object.defineProperty.value (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:50:18)
W20161026-21:37:12.916(-5)? (STDERR)     at /Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:53:10
W20161026-21:37:12.917(-5)? (STDERR)     at webpackUniversalModuleDefinition (/Users/frederickwells/travelcollide/collide-travel/node_modules/react-summernote/dist/react-summernote.js:3:20)

```

Any idea how to get around this?

**Comment by kevinrademan** [comment]
+1

**Comment by Vnkitaev** [comment]
Unfortunately Summernote only uses the browser navigator, so there is no possibility for server-side-rendering.

**Comment by StanleySong** [comment]
try this to work around with ssr
import React, { Component } from 'react';

```class HtmlEditor extends Component {
    constructor(props) {
        super(props);
        if (typeof window !== 'undefined') {
          this.ReactSummernote = require('react-summernote').default;
        }
        this.state = {
            placeholder: 'Please write something here...',
            activeTab: '1'
        };
      }

  onChange(content) {
    console.log('onChange', content);
  }

  render() {
    const ReactSummernote = this.ReactSummernote;
    if (typeof window !== 'undefined' && ReactSummernote) {
        return (
            <ReactSummernote
              value="Default value"
              options={{
                height: 350,
                dialogsInBody: true,
                toolbar: [
                  ['style', ['style']],
                  ['font', ['bold', 'underline', 'clear']],
                  ['fontname', ['fontname']],
                  ['para', ['ul', 'ol', 'paragraph']],
                  ['table', ['table']],
                  ['insert', ['link', 'picture', 'video']],
                  ['view', ['fullscreen', 'codeview']]
                ]
              }}
              onChange={this.onChange}
            />
          );
    }
    else {
        return <textarea />;
    }
  }
}

export default HtmlEditor;
```

**Comment by housten0219** [comment]
I try use @StanleySong solution, But i get another error
`$node.attr(...).tooltip is not a function
TypeError: $node.attr(...).tooltip is not a function
    at http://localhost:3002/_next/-/page/blog-release.js:89923:10
    at Renderer.render (node_modules/react-summernote/dist/react-summernote.js:11815:0)
    at http://localhost:3002/_next/-/page/blog-release.js:89867:17
    at Array.forEach (<anonymous>)
    at Renderer.render (node_modules/react-summernote/dist/react-summernote.js:11809:0)
    at http://localhost:3002/_next/-/page/blog-release.js:93252:12
    at Buttons.build (node_modules/react-summernote/dist/react-summernote.js:15688:0)
    at Context.invoke (node_modules/react-summernote/dist/react-summernote.js:11736:0)
    at Toolbar.initialize (node_modules/react-summernote/dist/react-summernote.js:15820:0)
    at Context.initializeModule (node_modules/react-summernote/dist/react-summernote.js:11665:0)

    in ReactSummernote (at ContentField.js:63)
    in div (at ContentField.js:61)
    in ContentField (at BlogReleaseLayout.js:88)
    in form (at BlogReleaseLayout.js:64)
    in div (at BlogReleaseLayout.js:63)
    in div (at BlogReleaseLayout.js:62)
    in div (at BlogReleaseLayout.js:60)
    in div (at BlogReleaseLayout.js:58)
    in div (at Layout.js:6)
    in Layout (at BlogReleaseLayout.js:55)
    in BlogReleaseLayout (at blog-release.js:385)
    in BlogReleaseController (created by withRouter(BlogReleaseController))
    in withRouter(BlogReleaseController) (created by App)
    in Container (created by App)
    in App
    in AppContainer`

Who can help me?

**Comment by timknapp12** [comment]
Any updates on this? I'm getting the same error and @StanleySong 's work around did not work for me unfortunately. I'm using nextjs with ssr
