### ISSUE TITLE
Is React-Bootstrap supported?

### ISSUE THREAD

**Issue by mdstaff** [Vnkitaev/react-summernote#14]
Hello there,

Firstly, thanks for your hard work on this repository.  I'm trying to use your plugin in an existing app.

- I'm having trouble getting WebPack 1.x to load both react-summernote and react-bootstrap.
  - The browser console lists the following error: `TypeError: $node.attr(...).tooltip is not a function(…)`

After inspecting the error the problem is in the summernote core where it defines the summernote.ui.button.  I've tried importing the Tooltip module from react-boostrap in my app but that didn't work.  It seems likely that my WebPack configuration is missing something.  Do you have any suggestions?

Thanks much,
Matt

**Comment by mdstaff** [comment]
Turns out react-bootstrap tries to implement bootstrap features using react components

**Comment by george-norris-salesforce** [comment]
Would love to have React-Bootstrap supported..
