### ISSUE TITLE
Can fail when multiple editors on one page

### ISSUE THREAD

**Issue by mbeech** [Vnkitaev/react-summernote#15]
I have four editors on one page, some of them occasionally fail to display as the IDs clash

```this.uid = `react-summernote-${Date.now()}`;```

I'd suggest adding some random element, or making the uid customisable by the user to avoid this.

**Comment by Vnkitaev** [comment]
Great note, I'll fix it very soon, thank you!

**Comment by Vnkitaev** [comment]
I've fixed this in a 1.0.5 version, so you should try it, everything's gonna be fine.
