### ISSUE TITLE
React-Summernote too heavy (over 600kb)

### ISSUE THREAD

**Issue by tbson** [Vnkitaev/react-summernote#19]
After building my app using Webpack with production environment.
I found that react-summernote is the largest component (over 600kb) when summernote.min.js is around 94kb
....
react-summernote: 627.8 KB (18.2%)
react-dom: 507.97 KB (14.7%)
jquery: 260.93 KB (7.56%)
redux-form: 171.38 KB (4.97%)
react: 134.05 KB (3.88%)
lodash: 126.91 KB (3.68%)
....
Is this a big deal?

**Comment by Vnkitaev** [comment]
That's because of codemirror dependency, not a big deal.

But perhaps, I would be able not to import it in future version and let the users to decide whether to import it or not.
