### ISSUE TITLE
Can not using Link, Image, Video function

### ISSUE THREAD

**Issue by ronin1184** [Vnkitaev/react-summernote#2]
I can run summernote with other toolbar's function but Link, Image and Video function don't run (do nothing when I clicked on it). I think there are missing Bootstrap Javascript but when I import Bootstrap Javascript then it still not run.
Do you have any ideas?

**Comment by Vnkitaev** [comment]
Try to use `dialogsInBody: true` option
http://summernote.org/deep-dive/#dialogs

Example:
```javascript
<ReactSummernote
	options={{
		dialogsInBody: true
	}}
/>
```

**Comment by ronin1184** [comment]
That's work! Thank you very much.
