### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead

### ISSUE THREAD

**Issue by boosis** [Vnkitaev/react-summernote#28]
I have version `^2.0.0-rc.1` in my `packages.json` and everything works fine except this error message in the console.

**Comment by boosis** [comment]
FYI, culprit is this bit

> ReactSummernote.propTypes = {
	  value: _react.PropTypes.string,
	  defaultValue: _react.PropTypes.string,
	  className: _react.PropTypes.string,
	  options: _react.PropTypes.object,
	  onInit: _react.PropTypes.func,
	  onEnter: _react.PropTypes.func,
	  onFocus: _react.PropTypes.func,
	  onBlur: _react.PropTypes.func,
	  onKeyUp: _react.PropTypes.func,
	  onKeyDown: _react.PropTypes.func,
	  onPaste: _react.PropTypes.func,
	  onChange: _react.PropTypes.func,
	  onImageUpload: _react.PropTypes.func
	};

**Comment by Vnkitaev** [comment]
Hello, please use version ^2.0.0
