### ISSUE TITLE
style and fontname doesnt work

### ISSUE THREAD

**Issue by riftshock** [Vnkitaev/react-summernote#3]
toolbar: [
            ["style", ["style"]],
           ["fontname", ["fontname"]],
 ],

dropdown for style and selecting font style does'nt work..any ideas??thanks in advance =)
btw ur package was super helpful. thumbs up =)

**Comment by riftshock** [comment]
Its working now i just have to remove bootstap.js ...

**Comment by sandddyyyy** [comment]
I'm currently experiencing the same issue -- dropdowns are not working. I tried to remove these lines
`import "bootstrap/js/modal";`
`import "bootstrap/js/dropdown";`
`import "bootstrap/js/tooltip";`
which Vnkitaev added in the example/demo. Still, dropdown are not collapsing. What exactly did you do?

**Comment by renetanikolova** [comment]
You should import bootstrap using: 
require('bootstrap');
