### ISSUE TITLE
Use with Browserify `jQuery is not defined`?

### ISSUE THREAD

**Issue by george-norris-salesforce** [Vnkitaev/react-summernote#4]
How do I use this with Browserify? Getting a jQuery is not defined error.. although I've added jQuery

**Comment by Vnkitaev** [comment]
Unfortunately I have not used browserify.
But I can recommend try:

```javascript
window.$ = window.jQuery = require('jquery');
```

**Comment by krobing** [comment]
I had the same issue, and I have solved it using the `browserify-shim` module.
In the following way:

- after you have installed the module `browserify-shim`, you should put up the next fragment on the `package.json`:
```json
"browserify": {
    "transform": [
      "browserify-shim"
    ]
},
"browserify-shim": {
    "jquery": "global:jQuery",
    "react-summernote/lang/summernote-es-ES.js": {
      "depends": [
        "jquery:jQuery"
      ]
    }
},
```

- And if you use the `browserify` with `gulp`, set the transformer by browserify specifying on the settings that will use global elements (ej: window.$).

```javascript
var b = browserify('./assets/js/components/main.js')
    .transform(babelify, {
      presets: ['es2015', 'react']
    })
    .transform({
        global: true
    }, 'browserify-shim');

var watcher = watchify(b);
```
