### ISSUE TITLE
Decouple from bootstrap dependencies

### ISSUE THREAD

**Issue by igolden** [Vnkitaev/react-summernote#5]
Hey there!

First off,  great plugin. I'm using this in a production react app and I'm hoping to push this feature live.

1. I'm having trouble with bootstrap dependencies. I have these assets in our Rails app, and everything breaks when I render my standalone react app within that rails app. There's a conflict in Bootstraps (dropdown stop working, etc).

I'd like to remove the dependencies from of bootstrap from your module. How would you recommend me doing this?

2. With bootstrap 4 in (stable) alpha, you may want to add an option for this. Just a thought!

Thanks for your help.
Cheers!

**Comment by Vnkitaev** [comment]
Hey, this is actually a good idea! I'll implement it in upcoming(или next) updates.

**Comment by Vnkitaev** [comment]
That was implemented some time ago, check this [commit](https://github.com/Vnkitaev/react-summernote/commit/ab34263fdeed0e35ccc23e396fad36485ef1a8d7)
