### ISSUE TITLE
server rendering breaks component. "TypeError: Cannot read property 'modal' of undefined"

### ISSUE THREAD

**Issue by koryteg** [Vnkitaev/react-summernote#6]
I get `"TypeError: Cannot read property 'modal' of undefined"` when server rendering a component with this. the component's state has the wysiwyg not even open on load. but still wont render. 

might work to hold off initializing summernote until it hits the `componentDidMount` hook. but I am just guessing at this without source diving.

**Comment by koryteg** [comment]
great job closing without responding. so no thoughts at all. no reference to another PR? anything here?

**Comment by Vnkitaev** [comment]
It's impossible to use Summernote with server-side rendering because of client-side dependencies
