### ISSUE TITLE
How can I bind a new event "removeMedia" with the delete button?

### ISSUE THREAD

**Issue by GJ2511** [Vnkitaev/react-summernote#7]
How Can I know that media added on summernote has been removed? (from delete button which we get when we click over the image OR when we press backspace)

**Comment by Vnkitaev** [comment]
Try using the onChange event and compare the contents

**Comment by GJ2511** [comment]
Are you serious you want me to find out <img> from HTML string?

What if I have many Images at one time, then how would I know which image is deleted?

**Comment by Vnkitaev** [comment]
Well, summernote doesn't have such event, you might want to look at [this](http://summernote.org/deep-dive/#callbacks)

You're always free to create an issue in the main [Summernote](https://github.com/summernote/summernote) repository
