### ISSUE TITLE
Mp4 Videos duplicate on Enter Key Press

### ISSUE THREAD

**Issue by riftshock** [Vnkitaev/react-summernote#8]
Hey Ivan Kitaev, loved your work dude.

Anyway there's a bug on summernote. It duplicates an mp4 video on enter key press after inserting it to summernote.  Then the mp4 video can hardly be deleted after upload. But it works fine on youtube, dailymotion and etc.

Any ideas about this?anyway thanks man great work =)

**Comment by Vnkitaev** [comment]
Seems like this bug occurs somewhere inside Summernote itself, you can create an issue in the main  [Summernote](https://github.com/summernote/summernote) repository. 

Once they will fix it, I'll update this repo. Regards!
